// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/document/document.proto

package document

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Indices              []string `protobuf:"bytes,5,rep,name=indices,proto3" json:"indices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c9d4e2317dc82b1, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Document) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *Document) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Document) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Document) GetIndices() []string {
	if m != nil {
		return m.Indices
	}
	return nil
}

type DocumentTransferRequest struct {
	Request              *Document `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentTransferRequest) Reset()         { *m = DocumentTransferRequest{} }
func (m *DocumentTransferRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentTransferRequest) ProtoMessage()    {}
func (*DocumentTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c9d4e2317dc82b1, []int{1}
}

func (m *DocumentTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentTransferRequest.Unmarshal(m, b)
}
func (m *DocumentTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentTransferRequest.Marshal(b, m, deterministic)
}
func (m *DocumentTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentTransferRequest.Merge(m, src)
}
func (m *DocumentTransferRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentTransferRequest.Size(m)
}
func (m *DocumentTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentTransferRequest proto.InternalMessageInfo

func (m *DocumentTransferRequest) GetRequest() *Document {
	if m != nil {
		return m.Request
	}
	return nil
}

type DocumentTransferResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentTransferResponse) Reset()         { *m = DocumentTransferResponse{} }
func (m *DocumentTransferResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentTransferResponse) ProtoMessage()    {}
func (*DocumentTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c9d4e2317dc82b1, []int{2}
}

func (m *DocumentTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentTransferResponse.Unmarshal(m, b)
}
func (m *DocumentTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentTransferResponse.Marshal(b, m, deterministic)
}
func (m *DocumentTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentTransferResponse.Merge(m, src)
}
func (m *DocumentTransferResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentTransferResponse.Size(m)
}
func (m *DocumentTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentTransferResponse proto.InternalMessageInfo

func (m *DocumentTransferResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "pb.Document")
	proto.RegisterType((*DocumentTransferRequest)(nil), "pb.DocumentTransferRequest")
	proto.RegisterType((*DocumentTransferResponse)(nil), "pb.DocumentTransferResponse")
}

func init() { proto.RegisterFile("pb/document/document.proto", fileDescriptor_7c9d4e2317dc82b1) }

var fileDescriptor_7c9d4e2317dc82b1 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x75, 0xdb, 0x6a, 0x77, 0xc7, 0x82, 0x32, 0x17, 0xc3, 0x5a, 0x64, 0xd9, 0x83, 0xec, 0x69,
	0x85, 0x0a, 0xde, 0x15, 0xef, 0x42, 0xf4, 0xe4, 0x2d, 0xc9, 0x8e, 0x10, 0x68, 0x93, 0x98, 0xa4,
	0xfe, 0x10, 0x7f, 0xb1, 0x34, 0x6d, 0x6a, 0xa9, 0xde, 0xde, 0x47, 0xf2, 0xe6, 0x0d, 0x03, 0xb5,
	0x93, 0x77, 0x83, 0x55, 0xeb, 0x15, 0x99, 0xb8, 0x07, 0xbd, 0xf3, 0x36, 0x5a, 0x1c, 0x39, 0xd9,
	0x7e, 0x17, 0x50, 0x3e, 0xef, 0x64, 0xac, 0xa1, 0x1c, 0x44, 0x14, 0x52, 0x04, 0x62, 0x45, 0x53,
	0x74, 0x15, 0xdf, 0x73, 0xbc, 0x01, 0x50, 0x76, 0xb9, 0x24, 0x15, 0xb5, 0x35, 0x6c, 0x94, 0xdc,
	0x03, 0x05, 0xe7, 0x50, 0x19, 0xb1, 0xa2, 0xe0, 0x84, 0x22, 0x36, 0x4e, 0xf6, 0xaf, 0x80, 0x08,
	0x93, 0x4d, 0x12, 0x9b, 0x34, 0x45, 0x37, 0xe3, 0x09, 0x23, 0x83, 0xa9, 0x36, 0x83, 0x56, 0x14,
	0xd8, 0x69, 0x33, 0xee, 0x2a, 0x9e, 0x69, 0xfb, 0x08, 0x57, 0xb9, 0xd3, 0x9b, 0x17, 0x26, 0x7c,
	0x90, 0xe7, 0xf4, 0xb9, 0xa6, 0x10, 0xf1, 0x16, 0xa6, 0x7e, 0x0b, 0x53, 0xc3, 0xf3, 0xc5, 0xac,
	0x77, 0xb2, 0xcf, 0xaf, 0x79, 0x36, 0xdb, 0x07, 0x60, 0x7f, 0x23, 0x82, 0xb3, 0x26, 0xd0, 0x66,
	0x4d, 0xbf, 0xc3, 0x79, 0xcd, 0xcc, 0x17, 0x12, 0x2e, 0xf2, 0xbf, 0x57, 0xf2, 0x5f, 0x5a, 0x11,
	0xbe, 0xc0, 0xe5, 0x71, 0x14, 0x5e, 0x1f, 0x4e, 0x3d, 0xea, 0x58, 0xcf, 0xff, 0x37, 0xb7, 0x13,
	0xda, 0x93, 0x27, 0x78, 0x2f, 0xf3, 0x25, 0xe4, 0x59, 0x3a, 0xc5, 0xfd, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6d, 0x47, 0x58, 0x00, 0xa8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentServiceClient interface {
	DocumentTransfer(ctx context.Context, in *DocumentTransferRequest, opts ...grpc.CallOption) (*DocumentTransferResponse, error)
}

type documentServiceClient struct {
	cc *grpc.ClientConn
}

func NewDocumentServiceClient(cc *grpc.ClientConn) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) DocumentTransfer(ctx context.Context, in *DocumentTransferRequest, opts ...grpc.CallOption) (*DocumentTransferResponse, error) {
	out := new(DocumentTransferResponse)
	err := c.cc.Invoke(ctx, "/pb.DocumentService/DocumentTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
type DocumentServiceServer interface {
	DocumentTransfer(context.Context, *DocumentTransferRequest) (*DocumentTransferResponse, error)
}

// UnimplementedDocumentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentServiceServer struct {
}

func (*UnimplementedDocumentServiceServer) DocumentTransfer(ctx context.Context, req *DocumentTransferRequest) (*DocumentTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocumentTransfer not implemented")
}

func RegisterDocumentServiceServer(s *grpc.Server, srv DocumentServiceServer) {
	s.RegisterService(&_DocumentService_serviceDesc, srv)
}

func _DocumentService_DocumentTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).DocumentTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DocumentService/DocumentTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).DocumentTransfer(ctx, req.(*DocumentTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocumentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DocumentTransfer",
			Handler:    _DocumentService_DocumentTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/document/document.proto",
}
