// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/connection/connection.proto

package connection

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Connection struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_57a91ee9fb8cf8cb, []int{0}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Connection) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ConnectionTransferRequest struct {
	Request              *Connection `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConnectionTransferRequest) Reset()         { *m = ConnectionTransferRequest{} }
func (m *ConnectionTransferRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionTransferRequest) ProtoMessage()    {}
func (*ConnectionTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57a91ee9fb8cf8cb, []int{1}
}

func (m *ConnectionTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionTransferRequest.Unmarshal(m, b)
}
func (m *ConnectionTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionTransferRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionTransferRequest.Merge(m, src)
}
func (m *ConnectionTransferRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionTransferRequest.Size(m)
}
func (m *ConnectionTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionTransferRequest proto.InternalMessageInfo

func (m *ConnectionTransferRequest) GetRequest() *Connection {
	if m != nil {
		return m.Request
	}
	return nil
}

type ConnectionTransferResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionTransferResponse) Reset()         { *m = ConnectionTransferResponse{} }
func (m *ConnectionTransferResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionTransferResponse) ProtoMessage()    {}
func (*ConnectionTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57a91ee9fb8cf8cb, []int{2}
}

func (m *ConnectionTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionTransferResponse.Unmarshal(m, b)
}
func (m *ConnectionTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionTransferResponse.Marshal(b, m, deterministic)
}
func (m *ConnectionTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionTransferResponse.Merge(m, src)
}
func (m *ConnectionTransferResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionTransferResponse.Size(m)
}
func (m *ConnectionTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionTransferResponse proto.InternalMessageInfo

func (m *ConnectionTransferResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Connection)(nil), "pb.Connection")
	proto.RegisterType((*ConnectionTransferRequest)(nil), "pb.ConnectionTransferRequest")
	proto.RegisterType((*ConnectionTransferResponse)(nil), "pb.ConnectionTransferResponse")
}

func init() { proto.RegisterFile("pb/connection/connection.proto", fileDescriptor_57a91ee9fb8cf8cb) }

var fileDescriptor_57a91ee9fb8cf8cb = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x48, 0xd2, 0x4f,
	0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x43, 0x62, 0xea, 0x15, 0x14, 0xe5, 0x97,
	0xe4, 0x0b, 0x31, 0x15, 0x24, 0x29, 0xb9, 0x71, 0x71, 0x39, 0xc3, 0xc5, 0x85, 0xa4, 0xb8, 0x38,
	0x52, 0x12, 0x4b, 0x12, 0x93, 0x12, 0x8b, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0,
	0x7c, 0x21, 0x19, 0x2e, 0xce, 0xbc, 0xc4, 0xdc, 0xd4, 0xe2, 0x82, 0xc4, 0xe4, 0x54, 0x09, 0x26,
	0xb0, 0x24, 0x42, 0x40, 0xc9, 0x95, 0x4b, 0x12, 0x61, 0x4e, 0x48, 0x51, 0x62, 0x5e, 0x71, 0x5a,
	0x6a, 0x51, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x06, 0x17, 0x7b, 0x11, 0x84, 0x09,
	0x36, 0x95, 0xdb, 0x88, 0x4f, 0xaf, 0x20, 0x49, 0x0f, 0xa1, 0x3e, 0x08, 0x26, 0xad, 0x64, 0xc1,
	0x25, 0x85, 0xcd, 0x98, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x90, 0xf3, 0x8a, 0xa0, 0x6c, 0x98,
	0xf3, 0x60, 0x7c, 0xa3, 0x2c, 0x2e, 0x41, 0x84, 0xce, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54,
	0xa1, 0x50, 0x2e, 0x21, 0x4c, 0xe3, 0x84, 0x64, 0x51, 0x6d, 0x47, 0x73, 0xad, 0x94, 0x1c, 0x2e,
	0x69, 0x88, 0x4d, 0x4a, 0x0c, 0x4e, 0x3c, 0x51, 0x5c, 0x88, 0xc0, 0x4c, 0x62, 0x03, 0x87, 0xa6,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x72, 0x02, 0x72, 0xa2, 0x6f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	ConnectionTransfer(ctx context.Context, in *ConnectionTransferRequest, opts ...grpc.CallOption) (*ConnectionTransferResponse, error)
}

type connectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewConnectionServiceClient(cc *grpc.ClientConn) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) ConnectionTransfer(ctx context.Context, in *ConnectionTransferRequest, opts ...grpc.CallOption) (*ConnectionTransferResponse, error) {
	out := new(ConnectionTransferResponse)
	err := c.cc.Invoke(ctx, "/pb.ConnectionService/ConnectionTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
type ConnectionServiceServer interface {
	ConnectionTransfer(context.Context, *ConnectionTransferRequest) (*ConnectionTransferResponse, error)
}

// UnimplementedConnectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConnectionServiceServer struct {
}

func (*UnimplementedConnectionServiceServer) ConnectionTransfer(ctx context.Context, req *ConnectionTransferRequest) (*ConnectionTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectionTransfer not implemented")
}

func RegisterConnectionServiceServer(s *grpc.Server, srv ConnectionServiceServer) {
	s.RegisterService(&_ConnectionService_serviceDesc, srv)
}

func _ConnectionService_ConnectionTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).ConnectionTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConnectionService/ConnectionTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).ConnectionTransfer(ctx, req.(*ConnectionTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectionTransfer",
			Handler:    _ConnectionService_ConnectionTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/connection/connection.proto",
}
